[package]
name = "simpler"
version = "0.1.1"
description = "Local-first Markdown notes app"
authors = ["Simpler contributors"]
edition = "2021"

[lib]
name = "simpler_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2.7.2"
tauri-plugin-updater = "2"

[target.'cfg(any(target_os = "linux", target_os = "dragonfly", target_os = "freebsd", target_os = "openbsd", target_os = "netbsd"))'.dependencies]
gtk = "0.18"
